Repository cryptic-game/cryptic-device, pull requests merged in 2019-06, with the labels that each got.

#22 changing error response
  app/models/file.py
  app/resources/device.py
  app/resources/file.py
  app/scheme.py
Labels: enhancement

#29 Issue/23 illegal mix of collations
  app/resources/file.py
Labels: bug

#30 merge experimental into master
  app/models/file.py
  app/resources/device.py
  app/resources/file.py
  app/scheme.py
Labels: bug, enhancement
